services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    networks:
      - network
networks:
  network:
    name: saltybread
    external: true